<script setup>
import { onMounted } from 'vue'

import Map from 'ol/Map.js'
import OSM from 'ol/source/OSM.js'
import TileLayer from 'ol/layer/Tile.js'
import View from 'ol/View.js'

// a good way of importing external framework CSS in modern JS is to add the CSS directly in the imports
// althought many framework now do that for you (OL doesn't)
import 'ol/ol.css'

let map
// the mounted lifecycle hook is run after the component is added to the page
// it's the perfect place to link OpenLayers to our HTML generated by Vue
onMounted(() => {
    // we keep track of OpenLayers instance with this.map attribute
    // (will be useful later when we will want to add event listeners)
    map = new Map({
        layers: [
            // adding OpenStreetMap as default layer
            new TileLayer({
                source: new OSM(),
            }),
        ],
        // this refers to the HTML ID of the div defined above in the template
        target: 'map',
        view: new View({
            // roughly the center of Switzerland
            center: [2660000, 1190000],
            // showing roughly the entire country
            zoom: 2,
            projection: 'EPSG:2056',
        }),
    })
})

// solution for first step, replacing OSM with a Swisstopo map, can be found here
// https://codesandbox.io/p/sandbox/basic-pixelkarte-farbe-627vvc
</script>

<template>
    <div id="map" />
</template>

<style scoped>
/* placing the map relative to its parent, and taking the maximum space it can.
 Its parent is App.vue component, and it is set to take the whole page, so our 
 map will take the whole screen too */
#map {
    position: relative;
    width: 100%;
    height: 100%;
}
</style>
